"""App configuration. Generated by Autonomous Product Studio (APS) - fill in the TODOs to ship."""
import os


class Settings:
    app_name: str = "AI Quiz Plateform"
    database_url: str = os.getenv("DATABASE_URL", "postgresql+psycopg://app:app@localhost:5432/app")
    debug: bool = os.getenv("DEBUG", "true").lower() == "true"


settings = Settings()
