"""FastAPI application entry point for AI Quiz Plateform.

Generated by Autonomous Product Studio (APS) - fill in the TODOs to ship.
"""
from fastapi import FastAPI

from app.api.routes import router

app = FastAPI(title="AI Quiz Plateform", version="0.1.0")
app.include_router(router)


@app.get("/")
def root():
    return {"app": "AI Quiz Plateform", "status": "scaffolded by APS"}
